/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author redes
 */
public class intRedes extends javax.swing.JFrame {
    private int graph[][] = new int[][] { {0, 4, 8, 6 }, 
                                          { 4, 0, 1, 1}, 
                                          { 8, 1, 0, 0}, 
                                          { 6, 1, 0, 0}};
    private int graph2[][] = new int[][] { {0, 2, 0, 4, 0, 5}, 
                                          { 2, 0, 3, 0, 1, 0}, 
                                          { 0, 3, 0, 0, 0, 4}, 
                                          { 4, 0, 0, 0, 2, 0},
                                          { 0, 1, 0, 2, 0, 0},
                                          { 5, 0, 4, 0, 0, 0}};
    private int graph3[][] = new int[][] { {0, 0, 5, 3, 0, 2, 0, 0}, 
                                          { 0, 0, 1, 0, 4, 0, 0, 0}, 
                                          { 5, 1, 0, 0, 0, 0, 0, 2}, 
                                          { 3, 0, 0, 0, 1, 0, 0, 0},
                                          { 0, 4, 0, 1, 0, 2, 0, 0},
                                          { 2, 0, 0, 0, 2, 0, 1, 0},
                                          { 0, 0, 0, 0, 0, 1, 0, 3},
                                          { 0, 0, 2, 0, 0, 0, 3, 0}};
    /**
     * Creates new form intRedes
     */
    
    private int contador = 0;
    private int contador2 = 0;
    private int contador3 = 0;
    public intRedes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTbPc4 = new javax.swing.JToggleButton();
        jTbPc1 = new javax.swing.JToggleButton();
        jTbPc2 = new javax.swing.JToggleButton();
        jTbPc3 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTbPc5 = new javax.swing.JToggleButton();
        jTbPc6 = new javax.swing.JToggleButton();
        jTbPc7 = new javax.swing.JToggleButton();
        jTbPc8 = new javax.swing.JToggleButton();
        jTbPc9 = new javax.swing.JToggleButton();
        jTbPc10 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTbPc11 = new javax.swing.JToggleButton();
        jTbPc12 = new javax.swing.JToggleButton();
        jTbPc13 = new javax.swing.JToggleButton();
        jTbPc14 = new javax.swing.JToggleButton();
        jTbPc15 = new javax.swing.JToggleButton();
        jTbPc16 = new javax.swing.JToggleButton();
        jTbPc17 = new javax.swing.JToggleButton();
        jTbPc18 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTbPc4.setText("R3");
        jTbPc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbPc4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTbPc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 60, 60));

        jTbPc1.setText("R0");
        jTbPc1.setToolTipText("");
        jTbPc1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTbPc1StateChanged(evt);
            }
        });
        jTbPc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbPc1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTbPc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 70, 60));

        jTbPc2.setText("R1");
        jTbPc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbPc2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTbPc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 70, 60));

        jTbPc3.setText("R2");
        jTbPc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbPc3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTbPc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 70, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/tpr.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 550, 530));

        jTabbedPane1.addTab("Topologia 1", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTbPc5.setText("R0");
        jTbPc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbPc5ActionPerformed(evt);
            }
        });
        jPanel2.add(jTbPc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 60, 60));

        jTbPc6.setText("R1");
        jTbPc6.setToolTipText("");
        jTbPc6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTbPc6StateChanged(evt);
            }
        });
        jTbPc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbPc6ActionPerformed(evt);
            }
        });
        jPanel2.add(jTbPc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 70, 60));

        jTbPc7.setText("R2");
        jTbPc7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbPc7ActionPerformed(evt);
            }
        });
        jPanel2.add(jTbPc7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 70, 60));

        jTbPc8.setText("R3");
        jTbPc8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbPc8ActionPerformed(evt);
            }
        });
        jPanel2.add(jTbPc8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 70, 60));

        jTbPc9.setText("R4");
        jTbPc9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbPc9ActionPerformed(evt);
            }
        });
        jPanel2.add(jTbPc9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 70, 60));

        jTbPc10.setText("R5");
        jTbPc10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbPc10ActionPerformed(evt);
            }
        });
        jPanel2.add(jTbPc10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 70, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/tpr2.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 590, 510));

        jTabbedPane1.addTab("Topologia 2", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTbPc11.setText("R0");
        jTbPc11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbPc11ActionPerformed(evt);
            }
        });
        jPanel3.add(jTbPc11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 60, 60));

        jTbPc12.setText("R1");
        jTbPc12.setToolTipText("");
        jTbPc12.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTbPc12StateChanged(evt);
            }
        });
        jTbPc12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbPc12ActionPerformed(evt);
            }
        });
        jPanel3.add(jTbPc12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 70, 60));

        jTbPc13.setText("R2");
        jTbPc13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbPc13ActionPerformed(evt);
            }
        });
        jPanel3.add(jTbPc13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 70, 60));

        jTbPc14.setText("R3");
        jTbPc14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbPc14ActionPerformed(evt);
            }
        });
        jPanel3.add(jTbPc14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 70, 60));

        jTbPc15.setText("R4");
        jTbPc15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbPc15ActionPerformed(evt);
            }
        });
        jPanel3.add(jTbPc15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 70, 60));

        jTbPc16.setText("R5");
        jTbPc16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbPc16ActionPerformed(evt);
            }
        });
        jPanel3.add(jTbPc16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 70, 60));

        jTbPc17.setText("R6");
        jTbPc17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbPc17ActionPerformed(evt);
            }
        });
        jPanel3.add(jTbPc17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 70, 60));

        jTbPc18.setText("R7");
        jTbPc18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbPc18ActionPerformed(evt);
            }
        });
        jPanel3.add(jTbPc18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 70, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/tpr32.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-47, 5, -1, -1));

        jTabbedPane1.addTab("Topologia 3", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTbPc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbPc1ActionPerformed
        // TODO add your handling code here:
        if(contador <=0){
            if(jTbPc1.isSelected() == true){
                estadoEnlace a = new estadoEnlace(graph[0].length);
            
            a.dijkstra(graph2, 0);
            contador++;
            
        }   else{
            contador--;
            
        }
        }else{
            if(jTbPc1.isSelected() == false){
            contador--;
            
        }else{
                JOptionPane.showMessageDialog(null, "Deselecciona el router y elige otro", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                jTbPc1.doClick();
                contador++;
            } 
            
        }
        
    }//GEN-LAST:event_jTbPc1ActionPerformed

    private void jTbPc1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTbPc1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTbPc1StateChanged

    private void jTbPc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbPc2ActionPerformed
        // TODO add your handling code here:
       if(contador <=0){
            if(jTbPc2.isSelected() == true){
                estadoEnlace a = new estadoEnlace(graph[0].length);
            
            a.dijkstra(graph2, 1);
            contador++;
            
        }   else{
            contador--;
            
        }
        }else{
            if(jTbPc2.isSelected() == false){
            contador--;
            
        }else{
                JOptionPane.showMessageDialog(null, "Deselecciona el router y elige otro", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                jTbPc2.doClick();
                contador++;
            } 
            
        }
    }//GEN-LAST:event_jTbPc2ActionPerformed

    private void jTbPc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbPc3ActionPerformed
        // TODO add your handling code here:
        if(contador <=0){
            if(jTbPc3.isSelected() == true){
            estadoEnlace a = new estadoEnlace(graph[0].length);
            
            a.dijkstra(graph2, 2);
            contador++;
            
        }   else{
            contador--;
            
        }
        }else{
            if(jTbPc3.isSelected() == false){
            contador--;
            
        }else{
                JOptionPane.showMessageDialog(null, "Deselecciona el router y elige otro", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                jTbPc3.doClick();
                contador++;
            } 
            
        }
        
    }//GEN-LAST:event_jTbPc3ActionPerformed

    private void jTbPc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbPc4ActionPerformed
        // TODO add your handling code here:
        if(contador <=0){
            if(jTbPc4.isSelected() == true){
            estadoEnlace a = new estadoEnlace(graph[0].length);
            
            a.dijkstra(graph2, 3);
            contador++;
            
        }   else{
            contador--;
            
        }
        }else{
            if(jTbPc4.isSelected() == false){
            contador--;
            
        }else{
                JOptionPane.showMessageDialog(null, "No selecciones mas de 1 PCS", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                jTbPc4.doClick();
                contador++;
            } 
            
        }
        
    }//GEN-LAST:event_jTbPc4ActionPerformed

    private void jTbPc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbPc5ActionPerformed
        // TODO add your handling code here:
        if(contador2 <=0){
            if(jTbPc5.isSelected() == true){
            estadoEnlace a = new estadoEnlace(graph2[0].length);
            
            a.dijkstra(graph2, 0);
            contador2++;
            
        }   else{
            contador2--;
            
        }
        }else{
            if(jTbPc5.isSelected() == false){
            contador2--;
            
        }else{
                JOptionPane.showMessageDialog(null, "No selecciones mas de 1 PCS", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                jTbPc5.doClick();
                contador2++;
            } 
            
        }
    }//GEN-LAST:event_jTbPc5ActionPerformed

    private void jTbPc6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTbPc6StateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTbPc6StateChanged

    private void jTbPc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbPc6ActionPerformed
        // TODO add your handling code here:
        if(contador2 <=0){
            if(jTbPc6.isSelected() == true){
            estadoEnlace a = new estadoEnlace(graph2[0].length);
            
            a.dijkstra(graph2, 1);
            contador2++;
            
        }   else{
            contador2--;
            
        }
        }else{
            if(jTbPc6.isSelected() == false){
            contador2--;
            
        }else{
                JOptionPane.showMessageDialog(null, "No selecciones mas de 1 PCS", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                jTbPc6.doClick();
                contador2++;
            } 
            
        }
    }//GEN-LAST:event_jTbPc6ActionPerformed

    private void jTbPc7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbPc7ActionPerformed
        // TODO add your handling code here:
        if(contador2 <=0){
            if(jTbPc7.isSelected() == true){
            estadoEnlace a = new estadoEnlace(graph2[0].length);
            
            a.dijkstra(graph2, 2);
            contador2++;
            
        }   else{
            contador2--;
            
        }
        }else{
            if(jTbPc7.isSelected() == false){
            contador2--;
            
        }else{
                JOptionPane.showMessageDialog(null, "No selecciones mas de 1 PCS", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                jTbPc7.doClick();
                contador2++;
            } 
            
        }
    }//GEN-LAST:event_jTbPc7ActionPerformed

    private void jTbPc8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbPc8ActionPerformed
        // TODO add your handling code here:
        if(contador2 <=0){
            if(jTbPc8.isSelected() == true){
            estadoEnlace a = new estadoEnlace(graph2[0].length);
            
            a.dijkstra(graph2, 3);
            contador2++;
            
        }   else{
            contador2--;
            
        }
        }else{
            if(jTbPc8.isSelected() == false){
            contador2--;
            
        }else{
                JOptionPane.showMessageDialog(null, "No selecciones mas de 1 PCS", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                jTbPc8.doClick();
                contador2++;
            } 
            
        }
    }//GEN-LAST:event_jTbPc8ActionPerformed

    private void jTbPc9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbPc9ActionPerformed
        // TODO add your handling code here:
        if(contador2 <=0){
            if(jTbPc9.isSelected() == true){
            estadoEnlace a = new estadoEnlace(graph2[0].length);
            
            a.dijkstra(graph2, 4);
            contador2++;
            
        }   else{
            contador2--;
            
        }
        }else{
            if(jTbPc9.isSelected() == false){
            contador2--;
            
        }else{
                JOptionPane.showMessageDialog(null, "No selecciones mas de 1 PCS", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                jTbPc9.doClick();
                contador++;
            } 
            
        }
    }//GEN-LAST:event_jTbPc9ActionPerformed

    private void jTbPc10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbPc10ActionPerformed
        // TODO add your handling code here:
        if(contador2 <=0){
            if(jTbPc10.isSelected() == true){
            estadoEnlace a = new estadoEnlace(graph2[0].length);
            
            a.dijkstra(graph2, 5);
            contador2++;
            
        }   else{
            contador2--;
            
        }
        }else{
            if(jTbPc10.isSelected() == false){
            contador2--;
            
        }else{
                JOptionPane.showMessageDialog(null, "No selecciones mas de 1 PCS", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                jTbPc10.doClick();
                contador2++;
            } 
            
        }
    }//GEN-LAST:event_jTbPc10ActionPerformed

    private void jTbPc11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbPc11ActionPerformed
        // TODO add your handling code here:
        if(contador3 <=0){
            if(jTbPc11.isSelected() == true){
            estadoEnlace a = new estadoEnlace(graph3[0].length);
            
            a.dijkstra(graph3, 0);
            contador3++;
            
        }   else{
            contador3--;
            
        }
        }else{
            if(jTbPc11.isSelected() == false){
            contador3--;
            
        }else{
                JOptionPane.showMessageDialog(null, "Deselecciona el router y elige otro", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                jTbPc11.doClick();
                contador3++;
            } 
            
        }
    }//GEN-LAST:event_jTbPc11ActionPerformed

    private void jTbPc12StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTbPc12StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTbPc12StateChanged

    private void jTbPc12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbPc12ActionPerformed
        // TODO add your handling code here:
        if(contador3 <=0){
            if(jTbPc12.isSelected() == true){
            estadoEnlace a = new estadoEnlace(graph3[0].length);
            
            a.dijkstra(graph3, 1);
            contador3++;
            
        }   else{
            contador3--;
            
        }
        }else{
            if(jTbPc12.isSelected() == false){
            contador3--;
            
        }else{
                JOptionPane.showMessageDialog(null, "Deselecciona el router y elige otro", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                jTbPc12.doClick();
                contador3++;
            } 
            
        }
    }//GEN-LAST:event_jTbPc12ActionPerformed

    private void jTbPc13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbPc13ActionPerformed
        // TODO add your handling code here:
        if(contador3 <=0){
            if(jTbPc13.isSelected() == true){
            estadoEnlace a = new estadoEnlace(graph3[0].length);
            
            a.dijkstra(graph3, 2);
            contador3++;
            
        }   else{
            contador3--;
            
        }
        }else{
            if(jTbPc13.isSelected() == false){
            contador3--;
            
        }else{
                JOptionPane.showMessageDialog(null, "Deselecciona el router y elige otro", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                jTbPc13.doClick();
                contador3++;
            } 
            
        }
    }//GEN-LAST:event_jTbPc13ActionPerformed

    private void jTbPc14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbPc14ActionPerformed
        // TODO add your handling code here:
        if(contador3 <=0){
            if(jTbPc14.isSelected() == true){
            estadoEnlace a = new estadoEnlace(graph3[0].length);
            
            a.dijkstra(graph3, 3);
            contador3++;
            
        }   else{
            contador3--;
            
        }
        }else{
            if(jTbPc14.isSelected() == false){
            contador3--;
            
        }else{
                JOptionPane.showMessageDialog(null, "Deselecciona el router y elige otro", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                jTbPc14.doClick();
                contador3++;
            } 
            
        }
    }//GEN-LAST:event_jTbPc14ActionPerformed

    private void jTbPc15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbPc15ActionPerformed
        // TODO add your handling code here:
        if(contador3 <=0){
            if(jTbPc15.isSelected() == true){
            estadoEnlace a = new estadoEnlace(graph3[0].length);
            
            a.dijkstra(graph3, 4);
            contador3++;
            
        }   else{
            contador3--;
            
        }
        }else{
            if(jTbPc15.isSelected() == false){
            contador3--;
            
        }else{
                JOptionPane.showMessageDialog(null, "Deselecciona el router y elige otro", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                jTbPc15.doClick();
                contador3++;
            } 
            
        }
    }//GEN-LAST:event_jTbPc15ActionPerformed

    private void jTbPc16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbPc16ActionPerformed
        // TODO add your handling code here:
        if(contador3 <=0){
            if(jTbPc16.isSelected() == true){
            estadoEnlace a = new estadoEnlace(graph3[0].length);
            
            a.dijkstra(graph3, 5);
            contador3++;
            
        }   else{
            contador3--;
            
        }
        }else{
            if(jTbPc16.isSelected() == false){
            contador3--;
            
        }else{
                JOptionPane.showMessageDialog(null, "Deselecciona el router y elige otro", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                jTbPc16.doClick();
                contador3++;
            } 
            
        }
    }//GEN-LAST:event_jTbPc16ActionPerformed

    private void jTbPc17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbPc17ActionPerformed
        // TODO add your handling code here:
        if(contador3 <=0){
            if(jTbPc17.isSelected() == true){
            estadoEnlace a = new estadoEnlace(graph3[0].length);
            
            a.dijkstra(graph3, 6);
            contador3++;
            
        }   else{
            contador3--;
            
        }
        }else{
            if(jTbPc17.isSelected() == false){
            contador3--;
            
        }else{
                JOptionPane.showMessageDialog(null, "Deselecciona el router y elige otro", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                jTbPc17.doClick();
                contador3++;
            } 
            
        }
    }//GEN-LAST:event_jTbPc17ActionPerformed

    private void jTbPc18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbPc18ActionPerformed
        // TODO add your handling code here:
        if(contador3 <=0){
            if(jTbPc18.isSelected() == true){
            estadoEnlace a = new estadoEnlace(graph3[0].length);
            
            a.dijkstra(graph3, 7);
            contador3++;
            
        }   else{
            contador3--;
            
        }
        }else{
            if(jTbPc18.isSelected() == false){
            contador3--;
            
        }else{
                JOptionPane.showMessageDialog(null, "Deselecciona el router y elige otro", "InfoBox: ", JOptionPane.INFORMATION_MESSAGE);
                jTbPc18.doClick();
                contador3++;
            } 
            
        }
    }//GEN-LAST:event_jTbPc18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(intRedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(intRedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(intRedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(intRedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new intRedes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jTbPc1;
    private javax.swing.JToggleButton jTbPc10;
    private javax.swing.JToggleButton jTbPc11;
    private javax.swing.JToggleButton jTbPc12;
    private javax.swing.JToggleButton jTbPc13;
    private javax.swing.JToggleButton jTbPc14;
    private javax.swing.JToggleButton jTbPc15;
    private javax.swing.JToggleButton jTbPc16;
    private javax.swing.JToggleButton jTbPc17;
    private javax.swing.JToggleButton jTbPc18;
    private javax.swing.JToggleButton jTbPc2;
    private javax.swing.JToggleButton jTbPc3;
    private javax.swing.JToggleButton jTbPc4;
    private javax.swing.JToggleButton jTbPc5;
    private javax.swing.JToggleButton jTbPc6;
    private javax.swing.JToggleButton jTbPc7;
    private javax.swing.JToggleButton jTbPc8;
    private javax.swing.JToggleButton jTbPc9;
    // End of variables declaration//GEN-END:variables
}
